WaterCompanyCet47.Web/Controllers/ConsumptionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WaterCompanyCet47.Web.Data;
using WaterCompanyCet47.Web.Data.Entities;
using WaterCompanyCet47.Web.Data.Repositories;
using WaterCompanyCet47.Web.Helpers;
using WaterCompanyCet47.Web.Models;

namespace WaterCompanyCet47.Web.Controllers
{
    [Authorize]
    public class ConsumptionsController : Controller
    {
        private readonly IConsumptionRepository _consumptionRepository;
        private readonly IUserHelper _userHelper;
        private readonly IEquipmentRepository _equipmentRepository;
        private readonly DataContext _dataContext;

        public ConsumptionsController(
            IConsumptionRepository consumptionRepository,
            IUserHelper userHelper,
            IEquipmentRepository equipmentRepository,
            DataContext dataContext)
        {
            _consumptionRepository = consumptionRepository;
            _userHelper = userHelper;
            _equipmentRepository = equipmentRepository;
            _dataContext = dataContext;
        }

        public async Task<IActionResult> Index()
        {

            var model = await _consumptionRepository.GetConsumptionAsync(this.User.Identity.Name);

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult ListAllCostumer()
        {
            return View(_userHelper.GetAll().OrderBy(u => u.FullName));
        }

        public async Task<IActionResult> AddConsumption(string id)
        {
            var user = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);
            if (await _userHelper.IsUserInRoleAsync(user, "Admin"))
            {
                if (id == null)
                {
                    return RedirectToAction("ListAllCostumer");
                }

                user = await _userHelper.GetByIdAsync(id);
                var model = new AddConsumptionViewModel
                {
                    Equipments = _equipmentRepository.GetComboEquipments(user.UserName),
                    Users = _userHelper.GetComboUsers(user.UserName)
                };
                return View(model);
            }
            else
            {
                var model = new AddConsumptionViewModel
                {
                    Equipments = _equipmentRepository.GetComboEquipments(this.User.Identity.Name)

                };
                return View(model);
            }

        }

        [HttpPost]
        public async Task<IActionResult> AddConsumption(AddConsumptionViewModel model)
        {
            if (model.UserId == "0")
            {
                this.ModelState.AddModelError(string.Empty, "Falta selecionar o consumidor");
                ViewBag.Message = string.Format("Falta selecionar o consumidor");
                return this.RedirectToAction("AddConsumption");
            }

            var user = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);

            if (await _userHelper.IsUserInRoleAsync(user, "Admin"))
            {
                user = await _userHelper.GetByIdAsync(model.UserId.ToString());
                await _consumptionRepository.AddItemToConsumptionAsync(model, user.UserName);
            }
            else
            {
                await _consumptionRepository.AddItemToConsumptionAsync(model, this.User.Identity.Name);
            }

            //var user = await _userHelper.GetByIdAsync(model.UserId.ToString());


            return this.RedirectToAction("Index");

        }

        // GET: Equipments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }



            //var consumption = await _consumptionRepository.GetByIdAsync(id.Value);

            var consumption = await _dataContext.Consumptions
                .Include(e => e.Equipment)
                .Where(u => u.Id == id)
                .FirstOrDefaultAsync();

            if (consumption == null)
            {
                return NotFound();
            }

            return View(consumption);
        }

        // GET: Consumptions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (InvoiceExists(id.Value) == true)
            {
                return RedirectToAction("Index");
            }

            var consumption = await _consumptionRepository.GetByIdAsync(id.Value);
            if (consumption == null)
            {
                return NotFound();
            }

            var model = new ModifyConsumptionViewModel
            {
                ConsumptionValue = consumption.ConsumptionValue,
                ForBegin = consumption.ForBegin,
                ForEnd = consumption.ForEnd,
                User = consumption.User,
                Equipments = _equipmentRepository.GetComboEquipments(this.User.Identity.Name)
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ConsumptionDate,Equipment,ForBegin,ForEnd,ConsumptionValue")] Consumption consumption)
        {
            if (id != consumption.Id)
            {
                return NotFound();
            }

            try
            {
                consumption.Equipment = await _equipmentRepository.GetByIdAsync(id);
                consumption.User = await _userHelper.GetByIdAsync(id.ToString());
                consumption.ConsumptionDate = DateTime.UtcNow;

                await _consumptionRepository.UpdateAsync(consumption);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await _consumptionRepository.ExistsAsync(consumption.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Equipments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (InvoiceExists(id.Value) == true)
            {
                return RedirectToAction("Index");
            }

            var consumption = await _dataContext.Consumptions
                .Include(e => e.Equipment)
                .Where(u => u.Id == id)
                .FirstOrDefaultAsync();

            if (consumption == null)
            {
                return NotFound();
            }

            return View(consumption);
        }

        // POST: Equipments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var consumption = await _consumptionRepository.GetByIdAsync(id);
            await _consumptionRepository.DeleteAsync(consumption);

            return RedirectToAction(nameof(Index));
        }


        private bool InvoiceExists(int id)
        {
            //return this.equipmentRepository.ExistsAsync(view.Id);

            return _dataContext.Invoices.Any(e => e.Consumption.Id == id);
        }

    }
}

WaterCompanyCet47.Web/Controllers/EquipmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WaterCompanyCet47.Web.Data;
using WaterCompanyCet47.Web.Data.Entities;
using WaterCompanyCet47.Web.Data.Repositories;
using WaterCompanyCet47.Web.Helpers;
using WaterCompanyCet47.Web.Models;

namespace WaterCompanyCet47.Web.Controllers
{
    [Authorize]
    public class EquipmentsController : Controller
    {
        private readonly IEquipmentRepository _equipmentRepository;
        private readonly IUserHelper _userHelper;


        public EquipmentsController(IEquipmentRepository equipmentRepository, IUserHelper userHelper)
        {
            _equipmentRepository = equipmentRepository;
            _userHelper = userHelper;
        }



        // GET: Equipments
        public IActionResult Index()
        {
            var equipments = _equipmentRepository.GetAll()
                .Include(x => x.User)
                .OrderBy(e => e.WaterMetering);

            return View(equipments);

        }

        // GET: Equipments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _equipmentRepository.GetByIdAsync(id.Value);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        [Authorize(Roles = "Admin")]
        // GET: Equipments/Create
        public IActionResult Create()
        {
            var model = new AddEquipmentViewModel
            {
                Users = _userHelper.GetComboUsers()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddEquipmentViewModel model)
        {
            if (this.ModelState.IsValid)
            {

                await _equipmentRepository.AddEquipmentToEquipAsync(model, this.User.Identity.Name);

                ViewBag.Message = "Consumidor criado";

                return RedirectToAction("Index");
            }

            return this.View(model);
        }

        // GET: Equipments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _equipmentRepository.GetByIdAsync(id.Value);
            if (equipment == null)
            {
                return NotFound();
            }
            return View(equipment);
        }

        // POST: Equipments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,WaterMetering,Installation,Address")] Equipment equipment)
        {
            if (id != equipment.Id)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
            try
            {
                //equipment.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                equipment.User = await _userHelper.GetByIdAsync(id.ToString());
                await _equipmentRepository.UpdateAsync(equipment);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await _equipmentRepository.ExistsAsync(equipment.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Equipments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _equipmentRepository.GetByIdAsync(id.Value);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        // POST: Equipments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var equipment = await _equipmentRepository.GetByIdAsync(id);
            await _equipmentRepository.DeleteAsync(equipment);

            return RedirectToAction(nameof(Index));
        }

        //private bool EquipmentExists(int id)
        //{
        //    //return this.equipmentRepository.ExistsAsync(view.Id);

        //    //return this.Equipments.Any(e => e.Id == id);
        //}
    }
}

WaterCompanyCet47.Web/Controllers/InvoicesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using WaterCompanyCet47.Web.Data;
using WaterCompanyCet47.Web.Data.Entities;
using WaterCompanyCet47.Web.Data.Repositories;
using WaterCompanyCet47.Web.Helpers;
using WaterCompanyCet47.Web.Models;


namespace WaterCompanyCet47.Web.Controllers
{
    [Authorize]
    public class InvoicesController : Controller
    {
        private readonly DataContext _dataContext;
        private readonly IUserHelper _userHelper;
        private readonly IInvoiceRepository _invoiceRepository;
        private readonly IConsumptionRepository _consumptionRepository;
        private readonly IHostingEnvironment _hostingEnvironment;



        public InvoicesController(
            DataContext dataContext,
            IUserHelper userHelper,
            IInvoiceRepository invoiceRepository,
            IConsumptionRepository consumptionRepository,
            IHostingEnvironment hostingEnvironment)
        {
            _dataContext = dataContext;
            _userHelper = userHelper;
            _invoiceRepository = invoiceRepository;
            _consumptionRepository = consumptionRepository;
            _hostingEnvironment = hostingEnvironment;

        }

        public async Task<IActionResult> Index()
        {

            var user = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);
            if (await _userHelper.IsUserInRoleAsync(user, "Admin"))
            {
                return View(_userHelper.GetAll().OrderBy(u => u.FullName));
            }

            var invoices = _userHelper.GetAll()
            .Where(u => u.UserName == user.UserName)
            .OrderBy(u => u.FullName);
            return View(invoices);
        }

        public async Task<IActionResult> DataHistory(string id)
        {
            var user = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);
            if (await _userHelper.IsUserInRoleAsync(user, "Admin"))
            {
                var model = await _invoiceRepository.GetInvoiceAsync(id);
                return View(model);
            }
            else
            {
                var model = await _invoiceRepository.GetInvoiceAsync(user.Id);
                return View(model);
            }
            
        }

        public async Task<IActionResult> CalculateInvoice(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (InvoiceExists(id.Value) == true)
            {
                return RedirectToAction("Index");
            }

            var model = await _dataContext.Consumptions
                .Include(u => u.User)
                .ThenInclude(e => e.Equipments)
                .Where(u => u.Id == id).FirstOrDefaultAsync();

            if (model == null)
            {
                return NotFound();
            }

            double valorTotal = 0;

            for (int i = 1; i <= model.ConsumptionValue; i++)
            {
                if (i <= 5)
                {
                    valorTotal += 0.30;
                }
                else if (i > 5 && i <= 15)
                {
                    valorTotal += 0.80;
                }
                else if (i > 15 && i <= 25)
                {
                    valorTotal += 1.20;
                }
                else
                {
                    valorTotal += 1.60;
                }
            }

            var invoice = new Invoice
            {
                Equipment = model.Equipment,
                Consumption = model,
                InvoiceDate = DateTime.UtcNow,
                TotalAmount = valorTotal,
                User = model.User
            };

            _dataContext.Invoices.Add(invoice);

            var consumptionUpdate = await _dataContext.Consumptions.FirstOrDefaultAsync(c => c.Id == model.Id);

            var contact = new Consumption { Id = model.Id };
            contact.InvoiceIssued = true;
            _dataContext.Entry(contact).Property("InvoiceIssued").IsModified = true;


            await _dataContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }




        public async Task<IActionResult> Invoice(string id)
        {
            id = id.Replace(id.Substring(id.IndexOf(";")), "");

            var idDesenc = InvoiceSecurity.DecryptString(id);

            var model = await _dataContext.Invoices
                .Include(u => u.User)
                .Include(e => e.Equipment)
                .Include(c => c.Consumption)
                .Where(u => u.Id == Convert.ToInt32(idDesenc))
                .FirstOrDefaultAsync();

            return View(model);
        }



        private bool InvoiceExists(int id)
        {
            return _dataContext.Invoices.Any(e => e.Consumption.Id == id);
        }


    }
}

WaterCompanyCet47.Web/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Water Company</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/layout/assets/img/favicon.png" rel="icon">
    <link href="~/layout/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/layout/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/layout/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/layout/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/layout/assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/layout/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/layout/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/layout/assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/layout/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Bootslander - v3.0.0
    * Template URL: https://bootstrapmade.com/bootslander-free-bootstrap-landing-page-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />




</head>
<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center ">
        <div class="container d-flex align-items-center justify-content-between">

            <div class="logo">
                <h1><a asp-area="" asp-controller="Home" asp-action="Index"><span><i class="fas fa-tint"></i> WaterCompany</span></a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav class="nav-menu d-none d-lg-block">
                <ul>
                    <li class="active"><a asp-area="" asp-controller="Home" asp-action="Index">Início</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Sobre Nós</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Service">Serviços</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contato</a></li>
                    @*<li><a href="#gallery">Gallery</a></li>
                        <li><a href="#team">Team</a></li>
                        <li><a href="#pricing">Pricing</a></li>
                        <li class="drop-down">
                            <a href="">Drop Down</a>
                            <ul>
                                <li><a href="#">Drop Down 1</a></li>
                                <li class="drop-down">
                                    <a href="#">Drop Down 2</a>
                                    <ul>
                                        <li><a href="#">Deep Drop Down 1</a></li>
                                        <li><a href="#">Deep Drop Down 2</a></li>
                                        <li><a href="#">Deep Drop Down 3</a></li>
                                        <li><a href="#">Deep Drop Down 4</a></li>
                                        <li><a href="#">Deep Drop Down 5</a></li>
                                    </ul>
                                </li>
                                <li><a href="#">Drop Down 3</a></li>
                                <li><a href="#">Drop Down 4</a></li>
                                <li><a href="#">Drop Down 5</a></li>
                            </ul>
                        </li>
                    *@


                    @if (this.User.IsInRole("Admin"))
                    {
                        <li class="drop-down">
                            <a href="">Área do Administrador</a>
                            <ul>
                                <li class="drop-down">
                                    <a href="#">Consumidor</a>
                                    <ul>
                                        <li><a asp-controller="Account" asp-action="Index">Listar Todos Consumidores</a></li>
                                        <li><a asp-controller="Account" asp-action="Register">Registar Novo Consumidor</a></li>
                                    </ul>
                                </li>
                                <li class="drop-down">
                                    <a href="#">Contador</a>
                                    <ul>
                                        <li><a asp-area="" asp-controller="Equipments" asp-action="Index">Listar Todos Contadores</a></li>
                                        <li><a asp-area="" asp-controller="Equipments" asp-action="Create">Registar Novo Contador</a></li>
                                    </ul>
                                </li>
                                <li class="drop-down">
                                    <a href="#">Consumo</a>
                                    <ul>
                                        <li><a asp-area="" asp-controller="Consumptions" asp-action="Index">Ver Histórico de Consumo</a></li>
                                        <li><a asp-area="" asp-controller="Consumptions" asp-action="AddConsumption">Registar Novo Consumo</a></li>
                                    </ul>
                                </li>
                                <li><a asp-area="" asp-controller="Invoices" asp-action="Index">Faturação</a></li>
                            </ul>
                        </li>
                    }

                    @if (this.User.IsInRole("Customer"))
                    {
                        <li class="drop-down">
                            <a href="">Área de Cliente</a>
                            <ul>
                                <li class="drop-down">
                                    <a href="#">Consumo</a>
                                    <ul>
                                        <li><a asp-area="" asp-controller="Consumptions" asp-action="Index">Ver Histórico de Consumo</a></li>
                                        <li><a asp-area="" asp-controller="Consumptions" asp-action="AddConsumption">Registar Novo Consumo</a></li>
                                    </ul>
                                </li>
                                <li> <a asp-area="" asp-controller="Invoices" asp-action="DataHistory">Faturação</a></li>

                            </ul>
                        </li>
                    }

                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li class="drop-down">
                            <a class="get-started-btn scrollto"><i class="fas fa-user-circle"></i></a>
                            <ul>
                                <li>
                                    <a>@this.User.Identity.Name</a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Account" asp-action="Profile">Ver Perfil</a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            </ul>
                        </li>
                    }
                    else
                    {

                        <li><a class="get-started-btn scrollto" asp-area="" asp-controller="Account" asp-action="Login"><i class="fas fa-user-circle"></i> Login</a></li>
                    }

                </ul>
            </nav><!-- .nav-menu -->

        </div>
    </header><!-- End Header -->



    @RenderBody()


    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-4 col-md-6">
                        <div class="footer-info">
                            <h3>WaterCompany</h3>
                            <p class="pb-3"><em>A sua nova companhia de água em Portugal</em></p>
                            <p>
                                Rua Jau <br>
                                1300-312 Lisboa<br><br>
                                <strong>Phone:</strong> +351 21 496 7700<br>
                                <strong>Email:</strong> geral@watercompany.com<br>
                            </p>
                            <div class="social-links mt-3">
                                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                            </div>
                        </div>
                    </div>




                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Links Úteis</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Início</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Sobre Nós</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Serviços</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Termos do Serviço</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Política de Privacidade</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Nossos Serviços</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Residencial</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Empresarial</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Estado</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">PME</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Rural</a></li>
                        </ul>
                    </div>


                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Nossa sede</h4>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3113.6829585881687!2d-9.190358348903443!3d38.70212627950111!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd1ecd1cdf51dba5%3A0xaaa77b600a1271fe!2sCINEL%20-%20Centro%20de%20Forma%C3%A7%C3%A3o%20Profissional%20da%20Ind%C3%BAstria%20Electr%C3%B3nica%2C%20Energia%2C%20Telecomunica%C3%A7%C3%B5es%20e%20Tecnologias%20da%20Informa%C3%A7%C3%A3o!5e0!3m2!1spt-BR!2spt!4v1610986753277!5m2!1spt-BR!2spt" width="450" height="200" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>


                    </div>


                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>WaterCompany</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                Trabalho elaborado apenas para fins académicos
                <br />
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="~/layout/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/layout/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/layout/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/layout/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/layout/assets/vendor/venobox/venobox.min.js"></script>
    <script src="~/layout/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="~/layout/assets/vendor/counterup/counterup.min.js"></script>
    <script src="~/layout/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/layout/assets/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="~/layout/assets/js/main.js"></script>



    @RenderSection("Scripts", required: false)



</body>
</html>